[tool.poetry]
name = "aivet-vision"
version = "0.1.0"
description = "The Eyes - Grimace detection, optical flow, gait analysis"
authors = ["Doolittle Collective <hello@doolittle.org>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24"
pydantic = "^2.0"
